doc-warnings: false
pep8:
  full: true
test-warnings: false
strictness: veryhigh
max-line-length: 120
autodetect: true
ignore-paths:
    - test
ignore-patterns:
    - src/dummy_miz.py
    - src/ui/qt_resource.py
python-targets:
    - 3