doc-warnings: true
pep8:
  options:
    max-line-length: 120
  full: true
mccabe:
  options:
    max-complexity: 10
test-warnings: false
strictness: veryhigh
max-line-length: 120
autodetect: true
ignore-paths:
    - test
ignore-patterns:
    - emft/dummy_miz.py
    - emft/resources/qt_resource.py
python-targets:
    - 3
pyroma:
  run: true
