doc-warnings: true
test-warnings: true
strictness: veryhigh
max-line-length: 120
autodetect: true
ignore-paths:
  - test
ignore-patterns:
  - ^dummy_miz.py$
  - ^qt_resource.py$
python-targets:
  - 3
pep8:
  full: true